Repository Nicolas-Cardozo/devops-aula07, pull requests merged in 2018-03, with the labels that each got.

#2 Integrar Requisitos V1.0
  docs/requisitos.md
Labels: analise

#4 Integrar Arquitetura V1.0
  docs/arquitetura.md
Labels: arquitetura

#6 Integrar implementação v1.0
  src/jogovelha.py
Labels: programacao

#8 Integrar testes v1.0
  docs/src/testes_inic.py
  docs/src/testes_jogar.py
Labels: testes

#18 Update jogovelha.py
  src/jogovelha.py
Labels: programacao

#16 V1.1 analise
  docs/requisitos.md
Labels: analise

#19 V1.1
  docs/requisitos.md
  docs/src/testes_inic.py
  docs/src/testes_jogar.py
  src/jogovelha.py
Labels: operacoes
